version: '3.5'
services:
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./resources/migrations/sql:/flyway/sql
      - ./docker/flyway/flyway.conf:/flyway/conf/flyway.conf

  product-catalog:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:80
    depends_on:
      - flyway

  product-catalog-worker:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev-worker
    volumes:
      - ./:/usr/src/app
networks:
  default:
    external:
      name: ecommsystem
