version: '3.5'
services:
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./resources/migrations/sql:/flyway/sql
      - ./docker/flyway/flyway.conf:/flyway/conf/flyway.conf
networks:
  default:
    external:
      name: ecommsystem
