version: '3.5'
services:
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./resources/migrations/sql:/flyway/sql
      - ./docker/flyway/flyway.conf:/flyway/conf/flyway.conf

  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    command:
      - 'mongod'

  rabbitmq:
    image: rabbitmq:3.7.4

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379

  api:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:80
    depends_on:
      - redis
      - mysql
      - rabbitmq

  worker:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev-worker
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
      - mysql
      - rabbitmq
networks:
  default:
    external:
      name: ecommsystem
