version: '3.5'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./dockler/mysql/data:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3.7.4

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379:6379

  api:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:80
    depends_on:
      - mysql
      - redis
      - worker

  worker:
    image: node:14
    working_dir: /usr/src/app
    environment:
      - APP_PORT=80
      - NODE_ENV=development
    command: yarn run dev-worker
    volumes:
      - ./:/usr/src/app
    ports:
      - 3002:80
    depends_on:
      - rabbitmq
      - mysql
      - redis
